### ISSUE TITLE
Handle simutaneous attacking

### ISSUE THREAD

**Issue by kkalavantavanich** [2110511-GameProg-2018/typing#30]
What happens when player and enemy both attack simultaneously?

__CASE__ player attacked: 
- [x] Player results in `hitted` animation being played instead of `attacking` animation
- [ ] Player combo doesn't fail

__CASE__ enemy attacked:
- [x] Enemy continues attack without entering `hitted` animation

**Comment by Krittakan** [comment]
use WaitForSeconds() not AnimationEvent
